language: php

sudo: false

notifications:
    email: deploy@peter-gribanov.ru

matrix:
    include:
        - php: 7.3
        - php: 7.2
        - php: 7.1
        - php: 7.0
        - php: 5.6
        - php: 5.5
          dist: trusty
        - php: 5.4
          dist: trusty
        - php: 5.3
          dist: precise
        - php: 5.2
          dist: precise

script:
    # very short
    - ./writer_stream_copy 128 1000 && ./writer_copy 128 1000 && ./writer_rename 128 1000
    # short
    - ./writer_stream_copy 1024 1000 && ./writer_copy 1024 1000 && ./writer_rename 1024 1000
    # medium
    - ./writer_stream_copy 10240 100 && ./writer_copy 10240 100 && ./writer_rename 10240 100
    # large
    - ./writer_stream_copy 102400 100 && ./writer_copy 102400 100 && ./writer_rename 102400 100
    # very large
    - ./writer_stream_copy 1048576 100 && ./writer_copy 1048576 100 && ./writer_rename 1048576 100
