#!/usr/bin/env php
<?php

class CopyWriter
{
    /**
     * @var string
     */
    private $filename;
    /**
     * @var string
     */
    private $tmp_filename;

    /**
     * @var resource
     */
    private $handle;

    /**
     * @param string $filename
     */
    function open($filename)
    {
        $this->filename = $filename;
        $this->tmp_filename = tempnam(sys_get_temp_dir(), basename($filename));
        $this->handle = gzopen($this->tmp_filename, 'wb9');
    }

    /**
     * @param string $data
     */
    function append($data)
    {
        gzwrite($this->handle, $data);
    }

    function finish()
    {
        gzclose($this->handle);
        $this->handle = null;
        copy($this->tmp_filename, $this->filename);
        unlink($this->tmp_filename);
    }
}

$writer = new CopyWriter();

if (empty($argv[1]) || !is_numeric($argv[1])) {
    throw new \Exception('Not set data size');
}

if (empty($argv[2]) || !is_numeric($argv[2])) {
    throw new \Exception('Not set total iterations');
}

$data_size = (int) $argv[1]; // in Mb
$data_size *= 1024;
$iterations = (int) $argv[2];

$data = str_repeat('1', 1024); // 1 Kb

printf("CopyWriter\n");
printf("Data size: %d Mb\n", $data_size);
printf("Iterations: %d\n", $iterations);

$filename = tempnam(sys_get_temp_dir(), 'test_writer');

// test
$start = microtime(true);
for ($i = $iterations; $i; $i--) {
    $writer->open($filename);
    for ($j = 0; $j <= $data_size; $j++) {
        $writer->append($data);
    }
    $writer->finish();
    unlink($filename);
}
printf("Write: %f\n".PHP_EOL, microtime(true) - $start);
